[build]
builder = "dockerfile"

[deploy]
startCommand = "python -m mie.main scheduler"
restartPolicyType = "always"
restartPolicyMaxRetries = 5

[env]
TELEGRAM_TOKEN = "8406348922:AAEewXECoJATJ-w9QoYvypkuctLg381_S1w"
TELEGRAM_CHAT_ID = "1186281649"
PYTHONUNBUFFERED = "1"
PORT = "8000"
