[build]
builder = "dockerfile"

[deploy]
startCommand = "python main.py"
restartPolicyType = "always"
restartPolicyMaxRetries = 5

[env]
TELEGRAM_TOKEN = "8406348922:AAEewXECoJATJ-w9QoYvypkuctLg381_S1w"
TELEGRAM_CHAT_ID = "1186281649"
ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}"
PYTHONUNBUFFERED = "1"
PORT = "8000"
